name: ci

on:
  push:
    branches: deployment-automation

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws/x7u7j5v7
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push Sentry Base image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/sentry/Dockerfile
          push: true
          tags: |
            rungutancommunity/sentry-base:latest
            public.ecr.aws/x7u7j5v7/sentry-base:latest
      - name: Build and push Sentry Relay image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/relay/Dockerfile
          push: true
          tags: |
            rungutancommunity/sentry-relay:latest
            public.ecr.aws/x7u7j5v7/sentry-relay:latest
      - name: Build and push Sentry Snuba image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/snuba/Dockerfile
          push: true
          tags: |
            rungutancommunity/sentry-snuba:latest
            public.ecr.aws/x7u7j5v7/sentry-snuba:latest
      - name: Build and push Bash image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/bash/Dockerfile
          push: true
          tags: |
            rungutancommunity/bash:latest
            public.ecr.aws/x7u7j5v7/bash:latest
      - name: Build and push ClickHouse Client image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/clickhouse-client/Dockerfile
          push: true
          tags: |
            rungutancommunity/clickhouse-client:latest
            public.ecr.aws/x7u7j5v7/clickhouse-client:latest


