name: add-cookbooks

on:
  push:
    tags:
    - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: apt-get update && apt-get install -y git rsync openssh-client build-essential python-dev python-pip
      - name: Install bundler
        run: cd opsworks/clickhouse/ && gem install bundler --no-document
      - name: Install gems
        run: cd opsworks/clickhouse/ && bundle install
      - name: Install berkshelf
        run: cd opsworks/clickhouse/ && gem install berkshelf -v '~> 6.3.4'
      - name: Package cookbook
        run: cd opsworks/clickhouse/ && berks package clickhouse-${GITHUB_REF##*/}.tar.gz
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${GITHUB_REF##*/}
          release_name: Release ${GITHUB_REF##*/}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: opsworks/clickhouse/clickhouse-${GITHUB_REF##*/}.tar.gz
          asset_name: clickhouse-${GITHUB_REF##*/}.tar.gz
          asset_content_type: application/tar+gzip
